resources:
  - url: !resource custom/tracker-card.js?v=0.1.5
    type: js
  - url: !resource custom/mini-media-player-bundle.js?v=0.9.5
    type: module
  - url: !resource custom/weather-card.js?v=1
    type: module
  - url: !resource custom/fold-entity-row.js?v=0636ee
    type: js
  - url: !resource custom/layout-card.js?v=7db164
    type: js

title: Home
views: 
  - !include home.yaml
  - !include weather.yaml
  - !include vacuum.yaml
  - !include settings.yaml
