- platform: template
  name: Garage door
  value_template: "{{ is_state('switch.sonoff_dual_power_2', 'on') }}"
  lock:
    service: switch.turn_off
    data:
      entity_id: switch.sonoff_dual_power_2
  unlock:
    service: switch.turn_on
    data:
      entity_id: switch.sonoff_dual_power_2
