- alias: Set dark theme for the night
  initial_state: ON
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service: frontend.set_theme
      data:
        name: dark_red

- alias: Lock gates after opening them
  initial_state: ON
  trigger:
    platform: mqtt
    topic: stat/sonoff-dual/POWER1
    payload: 'ON'
  action:
    - delay:
        seconds: 05
    - service: mqtt.publish
      data:
        topic: cmnd/sonoff-dual/POWER1
        payload: 'OFF'

- alias: Turn off garage door switch
  initial_state: ON
  trigger:
    platform: mqtt
    topic: stat/sonoff-dual/POWER2
    payload: 'ON'
  action:
    - delay:
        seconds: 05
    - service: mqtt.publish
      data:
        topic: cmnd/sonoff-dual/POWER2
        payload: 'OFF'
