homeassistant:
  name: Home

  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation

  unit_system: metric

  time_zone: Europe/Vilnius

  whitelist_external_dirs:
    - /config

  packages: !include_dir_named packages
