homeassistant:
  name: Home

  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation

  unit_system: metric

  time_zone: Europe/Vilnius

  whitelist_external_dirs:
    - /config

  packages: !include_dir_named components/packages

camera: !include_dir_merge_list components/camera
group: !include_dir_merge_list components/group
light: !include_dir_merge_list components/light
lock: !include_dir_merge_list components/lock
sensor: !include_dir_merge_list components/sensor
switch: !include_dir_merge_list components/switch

automation: !include_dir_merge_list automations
panel_iframe: !include panels/iframes.yaml
script: !include_dir_merge_list scripts
