homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 67
  unit_system: metric
  time_zone: Europe/Vilnius
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

config:

http:
  base_url: https://hass.saltis.duckdns.org

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

discovery:

mqtt:
  broker: 192.168.1.177
  port: 1883
  client_id: home-assistant
  keepalive: 60
  birth_message:
    topic: tele/hass1/LWT
    payload: Online
    qos: 1
    retain: true
  will_message:
    topic: tele/hass1/LWT
    payload: Offline
    qos: 1
    retain: true

conversation:

recorder:

history:

logbook:

map:

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api

sun:

tts:
  - platform: google

cloud:

influxdb:
  override_measurement: state
  max_retries: 10

# image_processing:
#   - platform: dlib_face_identify
#     source:
#       - entity_id: camera.motion_detection
#     faces:
#       Julius: /config/files/faces/Julius.jpg
#       Tetis: /config/files/faces/Tetis.jpg
#   - platform: facebox
#     ip_address: 192.168.1.177
#     port: 8080
#     source:
#       - entity_id: camera.motion_detection

# device_tracker:
#   - platform: thomson
#     host: 192.168.1.254
#     username: !secret gateway_username
#     password: !secret gateway_password

history_graph:
  fronius:
    name: Fronius Powerflow
    entities:
      - sensor.generation
      - sensor.consumption
      - sensor.voltage
    refresh: 60

panel_iframe: !include panels.yaml
camera: !include cameras.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
