# Weather prediction
- platform: yr

- platform: darksky
  api_key: !secret darksky_api
  forecast:
    - 1
    - 2
    - 3
    - 4
    - 5
  monitored_conditions:
    - icon
    - summary
    - nearest_storm_distance
    - nearest_storm_bearing
    - humidity
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - wind_speed
    - wind_bearing
    - precip_type
    - precip_probability
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - uv_index
    - daily_summary
    - pressure
    - visibility
  update_interval:
    minutes: 5

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

# Fronius
- platform: rest
  name: fronius
  resource: http://192.168.1.209/solar_api/v1/GetPowerFlowRealtimeData.fcgi
  json_attributes:
    - Body
  value_template: >-
    {{ value_json.Body.Data.Site.Meter_Location }}
  scan_interval: 300

- platform: template
  sensors:
    generation:
      value_template: >-
        {% if states.sensor.fronius.attributes.Body.Data.Site.P_PV %}
          {{ states.sensor.fronius.attributes.Body.Data.Site.P_PV | round | float /1000 }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: kWh
    consumption:
      value_template: >-
        {{ states.sensor.fronius.attributes.Body.Data.Site.P_Load | abs | round | float /1000 }}
      unit_of_measurement: kWh
    grid:
      value_template: >-
        {{ states.sensor.fronius.attributes.Body.Data.Site.P_Grid | round | float /1000 }}
      unit_of_measurement: kWh
    import:
      value_template: >-
        {% if states.sensor.fronius.attributes.Body.Data.Site.P_Grid > 0 %}
          {{ states.sensor.fronius.attributes.Body.Data.Site.P_Grid | round | float /1000 }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: kWh
    export:
      value_template: >-
        {% if states.sensor.fronius.attributes.Body.Data.Site.P_Grid < 0 %}
          {{ states.sensor.fronius.attributes.Body.Data.Site.P_Grid | abs | round | float /1000 }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: kWh

- platform: rest
  resource: http://192.168.1.209/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData
  name: voltage
  value_template: >-
    {% if value_json.Body.Data.UDC %}
      {{ value_json.Body.Data.UDC.Value | float }}
    {% endif %}
  unit_of_measurement: V
  scan_interval: 300

# - platform: fronius
#   host: 192.168.1.209
#   type: inverter
#   device: 1

- platform: mqtt
  name: Sonoff TH10 Temperature
  state_topic: tele/sonoff-th10/SENSOR
  value_template: >-
    {{ value_json.AM2301.Temperature | float }}
  unit_of_measurement: °C
  device_class: temperature

- platform: mqtt
  name: Sonoff TH10 Humidity
  state_topic: tele/sonoff-th10/SENSOR
  value_template: >-
    {{ value_json.AM2301.Humidity | float }}
  unit_of_measurement: '%'
  device_class: humidity
