resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: js
  - url: /customcards/github/kalkih/mini-graph-card-bundle.js?track=true
    type: module
  - url: /customcards/github/kalkih/simple-weather-card.bundle.js?track=true
    type: module
  - url: /customcards/github/custom-cards/text-divider-row.js?track=true
    type: module
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module

title: Home
views:
  - !include /config/lovelace/home.yaml
  - !include /config/lovelace/weather.yaml
  - !include /config/lovelace/vacuum.yaml
  - !include /config/lovelace/settings.yaml
