resources:
  - url: /local/resources/tracker-card.js
    type: js
  - url: /local/resources/mini-media-player-bundle.js
    type: module
  - url: /local/resources/mini-graph-card-bundle.js
    type: module
  - url: /local/resources/simple-weather-card.bundle.js
    type: module
  - url: /local/resources/text-divider-row.js
    type: module

title: Home
views: 
  - !include /config/lovelace/home.yaml
  - !include /config/lovelace/weather.yaml
  - !include /config/lovelace/vacuum.yaml
  - !include /config/lovelace/settings.yaml
