- platform: template
  sensors:
    vacuum_status:
      friendly_name: Status
      value_template: >-
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}

    vacuum_battery:
      friendly_name: Battery
      value_template: >-
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}
      icon_template: >-
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_icon }}
      unit_of_measurement: '%'
      device_class: battery

    vacuum_cleaning_time:
      friendly_name: Cleaning time
      value_template: >-
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time }}
      unit_of_measurement: min

    vacuum_cleaned_area:
      friendly_name: Cleaned area
      value_template: >-
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaned_area }}
      unit_of_measurement: m^2
      icon_template: mdi:broom

    vacuum_cleaning_count:
      friendly_name: Cleaning count
      value_template: >-
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_count }}
      icon_template: mdi:broom

    vacuum_main_brush_left:
      friendly_name: Main brush
      value_template: >-
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }}
      icon_template: >-
        {% if states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left > 10 %}
          mdi:checkbox-marked-circle
        {% else %}
          mdi:alert
        {% endif %}
      unit_of_measurement: h

    vacuum_side_brush_left:
      friendly_name: Side brush
      value_template: >-
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }}
      icon_template: >-
        {% if states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left > 10 %}
          mdi:checkbox-marked-circle
        {% else %}
          mdi:alert
        {% endif %}
      unit_of_measurement: h

    vacuum_filter_left:
      friendly_name: Filter
      value_template: >-
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }}
      icon_template: >-
        {% if states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left > 10 %}
          mdi:checkbox-marked-circle
        {% else %}
          mdi:alert
        {% endif %}
      unit_of_measurement: h

    vacuum_sensor_dirty_left:
      friendly_name: Dirt sensor
      value_template: >-
        {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.sensor_dirty_left }}
      icon_template: >-
        {% if states.vacuum.xiaomi_vacuum_cleaner.attributes.sensor_dirty_left > 10 %}
          mdi:checkbox-marked-circle
        {% else %}
          mdi:alert
        {% endif %}
      unit_of_measurement: h
