- platform: mqtt
  name: Sonoff TH10 Temperature
  state_topic: tele/sonoff-th10/SENSOR
  value_template: >-
    {{ value_json.AM2301.Temperature | float }}
  unit_of_measurement: °C
  device_class: temperature

- platform: mqtt
  name: Sonoff TH10 Humidity
  state_topic: tele/sonoff-th10/SENSOR
  value_template: >-
    {{ value_json.AM2301.Humidity | float }}
  unit_of_measurement: '%'
  device_class: humidity
