- platform: mqtt
  name: Sonoff TH10 power
  state_topic: sonoff-th10/stat/POWER
  command_topic: sonoff-th10/cmnd/POWER
  availability_topic: sonoff-th10/tele/LWT
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  payload_available: Online
  payload_not_available: Offline
  retain: false
