- alias: Lock gates after opening them
  initial_state: ON
  trigger:
    platform: mqtt
    topic: sonoff-dual/stat/POWER1
    payload: 'ON'
  action:
    - delay:
        seconds: 05
    - service: mqtt.publish
      data:
        topic: sonoff-dual/cmnd/POWER1
        payload: 'OFF'

- alias: Close garage doors
  initial_state: ON
  trigger:
    platform: mqtt
    topic: sonoff-dual/stat/POWER2
    payload: 'ON'
  action:
    - delay:
        seconds: 05
    - service: mqtt.publish
      data:
        topic: sonoff-dual/cmnd/POWER2
        payload: 'OFF'
