- alias: "Set default theme to noctis"
  initial_state: "on"
  hide_entity: false
  trigger:
    - platform: homeassistant
      event: start
  condition: []
  action:
    - service: frontend.set_theme
      data:
        name: "noctis"
